### ISSUE TITLE
Unify around a single legal boilerplate

### ISSUE THREAD

**Issue by jordanekay** [ayanonagon/Parsimmon#15]
I think people's Xcodes are set up differently...

**Comment by ayanonagon** [comment]
@jordanekay I just overthrew the original Xcode project structure and made the tests consume the Parsimmon code as a pod to make sure users won’t have issues integrating (had to declare almost everything public while doing this). Was there another issue with the Xcode set up? Let me know if the sample app and tests build and run for you locally! :octocat:
